<?php

/**
 * @file
 * Defines intstrux highwire field types.
 */

/**
 * Implements hook_menu().
 */
function intstrux_highwire_field_menu() {
  
  $items = array();
  
  $items['highwire_field/autocomplete/%/%'] = array(
    'title' => 'HighWire field autocomplete',
    'page callback' => 'intstrux_highwire_field_autocomplete',
    'page arguments' => array(3, 5),
    'access callback' => 'intstrux_highwire_field_browse_access',
    'access arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
  );
  
  // entity type, field name, entity id or bundle
  $items['highwire_field/browse/%/%/%'] = array(
    'title' => 'HighWire Articles Browser',
    'page arguments' => array(),
    'page callback' => 'intstrux_highwire_field_browse',
    'delivery callback' => 'intstrux_highwire_field_deliver_dialog',
    'access callback' => 'intstrux_highwire_field_browse_access',
    'access arguments' => array(2, 3, 4),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function intstrux_highwire_field_autocomplete($field_name, $string = '') {
  $matches = array();
  
  $hw = intstrux_highwire_initialize(NULL, 'opensearch/results');
  
  if($hw) {
    // required value is 1
    $hw->param('v', '1');
    // the searchTerms CQL search query, search by title
    $hw->param('cql', 'dc.title any (' . $string . ')');
    // output should be returned in JSON format.
    $hw->param('type', 'json');
    // set cache expiration
    $hw->parse(variable_get('intstrux_highwire_cache_lifetime', -1));
  
    $result = drupal_json_decode($hw->getContent());
  
    foreach($result['atom:feed']['atom:entry'] as $entry) {
      $id = intstrux_highwire_parse_pmid($entry);
      $title = check_plain($entry['atom:title']['$']);

      $matches[$title . ' [id:' . $id . ']'] = check_plain($title . ' [id: ' . $id . ']');
    }
  }
    
  drupal_json_output($matches);
}

/**
 * Access callback for intstrux highwire browser.
 */
function intstrux_highwire_field_browse_access($entity_type, $field_name, $entity_id_or_bundle = NULL) {
  return true;
}

/**
 * Implementation of hook_field_widget_info().
 */
function intstrux_highwire_field_field_widget_info() {
  return array(
    'intstrux_highwire_field_browser' => array(
      'label' => t('HighWire browser'),
      'field types' => array('highwire_article'),
      'behaviors' => array(
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function intstrux_highwire_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $entity_type = $element['#entity_type'];
  $entity_info = entity_get_info($entity_type);
  $eid = isset($form[$entity_info['entity keys']['id']]['#value']) ? $form[$entity_info['entity keys']['id']]['#value'] : NULL;
  $bundle = isset($form[$entity_info['entity keys']['bundle']]['#value']) ? $form[$entity_info['entity keys']['bundle']]['#value'] : NULL;
  
  $element['article_id'] = array(
    '#type' => 'textfield',
    '#default_value' => isset($items[$delta]['article_id']) ? $items[$delta]['article_id'] : NULL,
    '#title' => $element['#title'],
    '#value_callback' => 'intstrux_highwire_field_browser_value',
    '#autocomplete_path' => 'highwire_field/autocomplete/' . $element['#entity_type'] . '/' . $element['#field_name'] . '/' . ($eid ? $eid : ($bundle ? $bundle : 0)),
    '#attributes' => array(
      'rel' => array($element['#field_name'] . '-' . $delta),
      'class' => array('highwire-article-field', $element['#field_name'] . '-' . $delta),
      'data-field-name' => $element['#field_name'],
    ),
    '#element_validate' => array(
      'intstrux_highwire_field_browser_validate',
    ),
    '#field_name' => $element['#field_name'],
    '#maxlength' => 300,
  );
  
  // Button to browse videos.
  $element['actions']['browse'] = array(
    '#type' => 'button',
    '#attributes' => array(
      'class' => array('highwire-field-browse-button'),
      'rel' => $element['#field_name'] . '-' . $delta,
      'data-entity-type' => $entity_type,
      'data-bundle' => $element['#bundle'],
      'data-field-name' => $element['#field_name'],
      'data-entity-id' => is_null($eid) ? '0' : $eid,
    ),
    '#executes_submit_callback' => FALSE,
    '#limit_validation_errors' => array(),
    '#default_value' => t('Browse'),
    '#value_callback' => 'intstrux_highwire_field_button_value_callback',
    '#ajax' => array(
       'callback' => 'intstrux_highwire_field_ajax_browse_dialog_callback',
    ),
    '#name' => $element['#field_name'] . '-' . $delta,
  );
  
  $element['actions']['remove'] = array(
    '#type' => 'button',
    '#attributes' => array(
      'class' => array('highwire-field-remove-button'),
      'rel' => $element['#field_name'] . '-' . $delta,
      'data-entity-type' => $entity_type,
      'data-field-name' => $element['#field_name'],
      'data-entity-id' => is_null($eid) ? '0' : $eid,
    ),
    '#default_value' => t('Remove'),
    '#value_callback' => 'intstrux_highwire_field_button_value_callback',
    '#name' => $element['#field_name'] . '-' . $delta,
  );
  
  if (!isset($element['#default_value'])) {
    $element['actions']['remove']['#attributes']['disabled'] = 'disabled';
  }
  
  if (empty($intstrux_highwire_field_settings[$element['#field_name']])) {
    $intstrux_highwire_field_settings[$element['#field_name']] = array(
      'highwire_field' => array($element['#field_name'] => array(
        'entity_type' => $entity_type,
        'field_name' => $element['#field_name'],
        'entity_id' => is_null($eid) ? '0' : $eid,
      )),
    );
  }
  
  // not sure if I'm going to use ui library
  $element['article_id']['#attached']['library'] = array(
    array('system', 'ui.dialog'),
  );
  
  $element['article_id']['#attached']['css'] = array(
    drupal_get_path('module', 'intstrux_highwire_field') . '/css/highwire.css',
  );

  $element['article_id']['#attached']['js'] = array(
    drupal_get_path('module', 'intstrux_highwire_field') . '/js/highwire.js',
  );
  
  // add field element to javascript drupal settings
  $element['article_id']['#attached']['js'][] = array(
    'data' => $intstrux_highwire_field_settings[$element['#field_name']],
    'type' => 'setting',
  );
  
  return $element;
}

/**
 * Value callback for the buttons.
 *
 * @return null
 */
function intstrux_highwire_field_button_value_callback() {
  return NULL;
}

/**
 * Implements hook_field_is_empty().
 */
function intstrux_highwire_field_field_is_empty($item, $field) {
  return empty($item['article_id']);
}

/**
 * Callback for Brightcove field browser widget.
 * Will return a field value in "video-name [id:videoId]" format.
 *
 */
function intstrux_highwire_field_browser_value($element, $value, $form_state) {
  if (!$value && !$form_state['input']) {
    $value = $element['#default_value'];
  }
  if (((int) $value) > 1) {
    
    $article = intstrux_highwire_article_load($value);

    if(isset($article['atom:entry']) && !empty($article['atom:entry'])) {
      $id = intstrux_highwire_parse_pmid($article['atom:entry']);
      $title = $article['atom:entry']['atom:title']['$'];
      $value = check_plain($title) . " [id:{$id}]";
    }
  }
  
  return $value;
}

/**
 * Validate callback for the field.
 */
function intstrux_highwire_field_browser_validate($element, &$form_state) {
  $id = '';
  $value = $element['#value'];
  
  if (!empty($value)) {
    // Assign ID to the value.
    // 231289 [id:72431493001]
    $id = intstrux_highwire_parse_id($value);

    if (is_numeric($id)) {
      // Matched ID, check if the article exists.
      $article = intstrux_highwire_article_load($id);

      if (!isset($article['atom:entry']) && intstrux_highwire_parse_pmid($article['atom:entry']) != $id) {
        form_error($element, t('%name: Found no valid article with that title. Please note that it might take several minutes after the article has been add to HighWire press to appear in the API.', array('%name' => t($element['#title']))));
      }
    } else {
      form_error($element, t('%name: Found no valid article with that title. Please note that it might take several minutes after the article has been add to HighWire press to appear in the API.', array('%name' => t($element['#title']))));
    }
  } 
  
  form_set_value($element, $id, $form_state);
}

function intstrux_highwire_field_ajax_browse_dialog_callback($form, $form_state) {
  $entity_type = $form_state['triggering_element']['#attributes']['data-entity-type'];
  $bundle = $form_state['triggering_element']['#attributes']['data-bundle'];
  $field_name = $form_state['triggering_element']['#attributes']['data-field-name'];
  $entity_id = $form_state['triggering_element']['#attributes']['data-entity-id'];
  $field_rel = $form_state['triggering_element']['#attributes']['rel'];
  
  
  $title = t('HighWire Articles Browser');
  $id = 'highwire-browse-dialog';
  $selector = '<div id="' . $id . '">';
  $path = url("highwire_field/browse/{$entity_type}/{$field_name}/" . ($entity_id ? $entity_id : ($bundle ? $bundle : 0)));
  
  $commands = array();
  $commands[] = ajax_command_intstrux_dialog($title, $id, $selector, $path, $field_rel, NULL, TRUE);
  return array('#type' => 'ajax', '#commands' => $commands);
}

function intstrux_highwire_field_ajax_browse_dialog_close_callback($form, $form_state) {
  $selector = '#browse-dialog';
  $data = check_plain($form_state['values']['title']) . ' [id:' . check_plain($form_state['values']['id']) . ']';
  $dialog_type = 'browse';

  $commands = array();
  $commands[] = ajax_command_intstrux_close_dialog($selector, $data, NULL, $dialog_type);
  return array('#type' => 'ajax', '#commands' => $commands);
}

function intstrux_highwire_field_browse() {

  // default result


  $filter_form = drupal_get_form('intstrux_highwire_field_filter_form');
  $filter_form = drupal_render($filter_form);

  return $filter_form;
}

function intstrux_highwire_field_deliver_dialog($page) {
  if (is_array($page)) {
    $page = drupal_render($page);
  }
  $output = '<html><head><title></title>' . drupal_get_css() . drupal_get_js() . '</head><body class="dialog">' . $page . '</body></html>';
  print $output;
}

/**
 * Implements hook_field_info().
 */
function intstrux_highwire_field_field_info() {
  return array(
   'highwire_article' => array(
     'label' => t('HighWire Article'),
     'description' => t('Browse and select article at HighWire Press.'),
     'settings' => array(),
     'instance_settings' => array(),
     'default_widget' => 'intstrux_highwire_field_browser',
     'default_formatter' => 'intstrux_highwire_default',
    ),
  );
}

/**
 * Implementation of hook_field_formatter_info().
 */
function intstrux_highwire_field_field_formatter_info() {
  $formatters = array();

  $formatters['intstrux_highwire_default'] = array(
    'label' => t('Article title (link)'),
    'description' => t('Display the title of the referenced article as a link to the node page.'),
    'field types' => array('highwire_article'),
  );
  
  $formatters['intstrux_highwire_plain'] = array(
    'label' => t('Article title (no link)'),
    'description' => t('Display the title of the referenced article as plain text.'),
    'field types' => array('highwire_article'),
  );
  
  $formatters['intstrux_highwire_abstract'] = array(
    'label' => t('Article abstract'),
    'description' => t('Display the abstract of the referenced article.'),
    'field types' => array('highwire_article'),
  );
  
  $formatters['intstrux_highwire_full'] = array(
    'label' => t('Article description'),
    'description' => t('Display the entire content of the referenced article.'),
    'field types' => array('highwire_article'),
  );    
  
  $formatters['intstrux_highwire_precis'] = array(
    'label' => t('Article precis'),
    'description' => t('Display the precis of the referenced article.'),
    'field types' => array('highwire_article'),
  );  
  
  $formatters['intstrux_highwire_pmid'] = array(
    'label' => t('Article pmid'),
    'description' => t('Display the referenced article pmid'),
    'field types' => array('highwire_article'),
  );
  
  return $formatters;
}

/**
 * Implements hook_field_formatter_view().
 *
 * @see intstrux_highwire_field_field_formatter_info()
 */
function intstrux_highwire_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  foreach ($items as $delta => $item) {
    $article_id = $item['article_id'];
  }
  
  switch ($display['type']) {
    case 'intstrux_highwire_default':
      if(isset($article_id)) {
        $article = intstrux_highwire_article_load($article_id);
        $title = check_plain($article['atom:entry']['atom:title']['$']);
        $link = intstrux_highwire_parse_link($article['atom:entry'], 'abstract', 'html');
        $element[0]['#markup'] = l($title, $link);
      }
      break;
    case 'intstrux_highwire_plain':
      if(isset($article_id)) {
        $article = intstrux_highwire_article_load($article_id);
        $title = check_plain($article['atom:entry']['atom:title']['$']);
        $element[0]['#markup'] = t($title);
      }
      break;
    case 'intstrux_highwire_abstract':
      if(isset($article_id)) {
        $abstract = intstrux_highwire_article_content_load($article_id, 'abstract', 'html');
        $abstract = intstrux_highwire_remove_tag('h1', 'id', 'article-title-1', $abstract);
        $element[0]['#markup'] = $abstract;
      }
      break;
    case 'intstrux_highwire_full':
      if(isset($article_id)) {
        $full = intstrux_highwire_article_content_load($article_id, 'full', 'html');
        $full = intstrux_highwire_remove_tag('h1', 'id', 'article-title-1', $full);
        $element[0]['#markup'] = $full;
      }
      break;    
    case 'intstrux_highwire_precis':
      if(isset($article_id)) {
        $precis = intstrux_highwire_article_content_load($article_id, 'precis', 'html');
        $precis = intstrux_highwire_remove_tag('h1', 'id', 'article-title-1', $precis);
        $element[0]['#markup'] = $precis;
      }
      break;
    case 'intstrux_highwire_pmid':
      if(isset($article_id)) {
        $element[0]['#markup'] = $article_id;
      }
      break;
  }
  
  return $element;
}

/**
 * Theme function returning a article field.
 */
function theme_intstrux_highwire_field_browser($element) {
  return $element['#children'];
}

/**
 * Implements hook_node_presave().
 */
function intstrux_highwire_field_node_presave($node) {
  
  $lang = $node->language;

  $article_id = 0;
  
  foreach($node as $delta => $item) {
    $field = field_info_field($delta);
    if(isset($field['type']) && $field['type'] == 'highwire_article') {
      $article_id = $node->{$delta}[$lang][0]['article_id'];
      break;
    }
  }
  
  if($article_id) {
    // load article by $article_id
    $article = intstrux_highwire_article_load($article_id);
  
    if(isset($article['atom:entry'])) {
      // save new title based on article title
      $node->title = check_plain($article['atom:entry']['atom:title']['$']);  
    }
  }
}

/**
 * Creates a Drupal Ajax 'intstrux_ui_dialog' command.
 *
 * The 'intstrux_ui_dialog' command instructs the client to display a jQuery UI
 * Dialog box.
 *
 * This command is implemented by Drupal.ajax.prototype.commands.ui()
 * defined in intstrux_highwire/intstrux_highwire_field/highwire.js.
 *
 * @param $title
 *   Optional. String, title of dialog.
 * @param $id
 *   Optional. Additional id to put on dialog.
 * @param $selector
 *   Selector of the element that should be made into a dialog.
 * @param $data
 *   Path if $iframe is TRUE.
 *   Html if $iframe is FALSE.
 * @param $field_rel
 *   Rel attribute of the corresponding field.
 * @param $settings
 *   TODO
 * @param $iframe
 *   Optional. Boolean, if the dialog should contain an iframe or other html content
 *
 * @return
 *   An array suitable for use with the ajax_render() function.
 */
function ajax_command_intstrux_dialog($title = 'Dialog', $id = NULL, $selector = '<div>', $data, $field_rel, $settings = NULL, $iframe = FALSE) {
  return array(
    'command' => 'intstrux_ui_dialog',
    'title' => $title,
    'id' => $id,
    'selector' => $selector,
    'data' => $data,
    'field_rel' => $field_rel,
    'settings' => $settings,
    'iframe' => $iframe,
  );
}

/**
 * Creates a Drupal Ajax 'intstrux_ui_close_dialog' command.
 *
 * The 'dialog' command instructs the client to close a jQuery UI
 * Dialog box.
 *
 * This command is implemented by Drupal.ajax.prototype.commands.ui()
 * defined in intstrux_highwire/intstrux_highwire_field/highwire.js.
 *
 * @param $selector
 *   Selector of the dialog that should be closed.
 * @param $data
 *   Data to send on close, depends on dialog type.
 * @param $settings
 *   TODO
 * @param $dialog_type
 *   Type of dialog to close.
 *
 * @return
 *   An array suitable for use with the ajax_render() function.
 */
function ajax_command_intstrux_close_dialog($selector = '<div>', $data, $settings = NULL, $dialog_type) {
  return array(
    'command' => 'intstrux_ui_close_dialog',
    'selector' => $selector,
    'data' => $data,
    'settings' => $settings,
    'dialog_type' => $dialog_type,
  );
}

/**
 * Filter form for article browser.
 */
function intstrux_highwire_field_filter_form($form, &$form_state) {
  $form['search'] = array(
    '#type' => 'fieldset',
    '#title' => t('Filter Articles'),
    '#collapsible' => TRUE,
    '#collapsed' => empty($_SESSION['intstrux_highwire_field_filter']) ? TRUE : FALSE,
  );

  $keywords = '';

  if (!empty($_SESSION['intstrux_highwire_field_filter']['keywords'])) {
    $keywords = $_SESSION['intstrux_highwire_field_filter']['keywords'];
  }

  $form['search']['keywords'] = array(
    '#type' => 'textfield',
    '#title' => t('Keywords'),
    '#size' => 25,
    '#default_value' => $keywords,
  );

  $form['search']['search'] = array(
    '#type' => 'radios',
    '#title' => t('Search in'),
    '#options' => array(
      'titles_desc' => t('Titles and descriptions'), 
      'titles' => t('Titles'), 
      'abstracts' => t('Abstracts'), 
      'descriptions' => t('Descriptions'), 
      'authors' => t('Authors'), 
    ),
    '#default_value' => isset($_SESSION['intstrux_highwire_field_filter']['search']) ? $_SESSION['intstrux_highwire_field_filter']['search'] : 'titles_desc',
    '#attributes' => array(
      'class' => array('search-radio'),
    ),
  );

  $form['search']['submit'] = array(
    '#type' => 'submit',
    '#name' => 'submit',
    '#default_value' => t('Filter'),
  );

  $form['search']['reset'] = array(
    '#type' => 'submit',
    '#name' => 'reset',
    '#default_value' => t('Reset'),
  );

  return $form;
}