<?php

/**
 * @file
 * Install, update and uninstall functions for the intstrux highwire field module.
 */

/**
 * Implements hook_field_schema().
 */
function intstrux_highwire_field_field_schema($field) {
  return array(
    'columns' => array(
      'article_id' => array(
        'type' => 'varchar',
        'length' => 25,
        'not null' => FALSE
      ),
    ),
    'indexes' => array(
      'article_id' => array('article_id'),
    ),
  );
}
